//----------------------------------------------------------------------------------------------------------------------
// Call of Cthulhu Weapons
//----------------------------------------------------------------------------------------------------------------------

import type { Knex } from 'knex';

//----------------------------------------------------------------------------------------------------------------------

export async function seed(knex : Knex) : Promise<void>
{
    const weapons = [
        {
            name: 'Bow and Arrows',
            damage: '1d6 + ({damageBonus} / 2)',
            range: ' yards',
            attacks: 1,
            ammo: 1,
            malfunction: 97,
            notes: '1920s, Modern',
            skill: 'Firearms (Bow)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Brass Knuckles',
            damage: '1d3 + 1 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Bullwhip',
            damage: '1d3 + ({damageBonus} / 2)',
            range: ' feet',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Whip)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Burning Torch',
            damage: '1d6 + burn',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Whip)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Chainsaw',
            damage: '2d8',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: 'Modern',
            skill: 'Fighting (Chainsaw)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Blackjack (Cosh, life-preserver)',
            damage: '1d8 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Club, large (baseball, cricket bat, poker)',
            damage: '1d8 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Club, small (nightstick)',
            damage: '1d6 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Crossbow',
            damage: '1d8 + 2',
            range: ' yards',
            attacks: '1/2',
            ammo: 1,
            malfunction: 96,
            notes: '1920s, Modern',
            skill: 'Firearms (Bow)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Garrote',
            damage: '1d6 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Garrote)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Hatchet/Sickle',
            damage: '1d6 + 1 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Axe)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Knife, Large (machete, etc.)',
            damage: '1d8 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Knife, Medium (carving knife, etc.)',
            damage: '1d4 + 2 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Knife, Small (switchblade, etc.)',
            damage: '1d4 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Live Wire, 2-volt charge',
            damage: '2d8 + stun',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: 95,
            notes: 'Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Mace Spray*',
            damage: 'stun',
            range: '6 feet',
            attacks: 1,
            ammo: 25,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Nunchaku',
            damage: '1d8 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Brawl)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Rock, Thrown',
            damage: '1d4 + ({damageBonus} / 2)',
            range: '{strength} / 5 yards',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Throw',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Shuriken',
            damage: '1d3 + ({damageBonus} / 2)',
            range: '{strength} / 5 yards',
            attacks: 2,
            ammo: null,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Throw',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Spear (cavalry lance)',
            damage: '1d8 + 1',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Spear)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Spear, Thrown',
            damage: '1d8 + ({damageBonus} / 2)',
            range: '{strength} / 5 yards',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: 'Rare',
            skill: 'Throw',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Sword, heavy (cavalry saber)',
            damage: '1d8 + 1 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Sword)',
            reference: 'Coc-IH:250',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Sword, medium (rapier, heavy epee)',
            damage: '1d6 + 1 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Sword)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Sword, light (sharpened fencing foil, sword cane)',
            damage: '1d6 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Sword)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Taser (contact)*',
            damage: '1d3 + stun',
            range: 'Touch',
            attacks: 1,
            ammo: 'Varies',
            malfunction: 97.0,
            notes: 'Modern',
            skill: 'Fighting (Brawl)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Taser (dart)',
            damage: '1d3 + stun',
            range: '15 feet',
            attacks: 1,
            ammo: 3,
            malfunction: 95.0,
            notes: 'Modern',
            skill: 'Firearms (Handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'War Boomerang',
            damage: '1d8 + 1 / 2 {damageBonus}',
            range: 'STR/5 yards',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: 'Rare',
            skill: 'Throw',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Wood Axe',
            damage: '1d8 + 2 + {damageBonus}',
            range: 'Touch',
            attacks: 1,
            ammo: null,
            malfunction: null,
            notes: '1920s, Modern',
            skill: 'Fighting (Axe)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Flintlock',
            damage: '1d6 + 1',
            range: '10 yards',
            attacks: '1/4',
            ammo: 1,
            malfunction: 95,
            notes: 'Rare',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.22 Short Automatic',
            damage: '1d6',
            range: '10 yards',
            attacks: '1 (3)',
            ammo: 6,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.25 Derringer (1B)',
            damage: '1d6',
            range: '3 yards',
            attacks: '1',
            ammo: 1,
            malfunction: 100,
            notes: '1920s',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.32 or 7.65mm Revolver',
            damage: '1d8',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 6,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.32 or 7.65mm Automatic',
            damage: '1d8',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 8,
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.357 Magnum Revolver',
            damage: '1d8 + 1d4',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 6,
            malfunction: 100,
            notes: 'Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.38 or 9mm Revolver',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 6,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.38 Automatic',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 8,
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Beretta M9',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 15,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Glock 17 9mm Auto',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 17,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Model P08 Luger',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 8,
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.41 Revolver',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 8,
            malfunction: 100,
            notes: '1920s, Rare',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.44 Magnum Revolver',
            damage: '1d10 + 1d4 + 2',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 6,
            malfunction: 100,
            notes: 'Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.45 Revolver',
            damage: '1d10 + 2',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 6,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '45 Automatic',
            damage: '1d10 + 2',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 7,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'IMI Desert Eagle',
            damage: '1d10 + 1d6 + 3',
            range: '15 yards',
            attacks: '1 (3)',
            ammo: 7,
            malfunction: 94,
            notes: 'Modern',
            skill: 'Firearms (handgun)',
            reference: 'CoC-IH:251',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.58 Springfield Rifle Musket',
            damage: '1d10 + 4',
            range: '60 yards',
            attacks: '1/4',
            ammo: 1,
            malfunction: 95,
            notes: 'Rare',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.22 Bolt-Action Rifle',
            damage: '1d6 + 1',
            range: '30 yards',
            attacks: '1',
            ammo: 6,
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.30 Lever-Action Carbine',
            damage: '2d6',
            range: '50 yards',
            attacks: '1',
            ammo: 6,
            malfunction: 98,
            notes: '1920s, Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.45 Martini-Henry Rifle',
            damage: '1d8 + 1d6 + 3',
            range: '80 yards',
            attacks: '1/3',
            ammo: 1,
            malfunction: 100,
            notes: '1920s',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: "Col. Moran's Air Rifle",
            damage: '2d6 + 1',
            range: '20 yards',
            attacks: '1/3',
            ammo: 1,
            malfunction: 88,
            notes: '1920s',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Garand M1, M2 Rifle',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: '1',
            ammo: 8,
            malfunction: 100,
            notes: 'WWII, Later',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'SKS Carbine',
            damage: '2d6 + 1',
            range: '90 yards',
            attacks: '1 (2)',
            ammo: 10,
            malfunction: 97,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.303 Lee Enfield',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: '1',
            ammo: 10,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.30-06 Bolt-Action Rifle',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: '1',
            ammo: 5,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.30-06 Semi-Auto Rifle',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: '1',
            ammo: 5,
            malfunction: 100,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.444 Marlin Rifle',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: '1',
            ammo: 5,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Elephant Gun (2B)',
            damage: '3d6 + 4',
            range: '100 yards',
            attacks: '1 or 2',
            ammo: 2,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '20-gauge Shotgun (2B)',
            damage: '2d6 / 1d6 / 1d3',
            range: '10/20/50 yards',
            attacks: '1 or 2',
            ammo: 2,
            malfunction: 100,
            notes: '1920s',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '16-gauge Shotgun (2B)',
            damage: '2d6 + 2 / 1d6 + 1 / 1d4',
            range: '10/20/50 yards',
            attacks: '1 or 2',
            ammo: 2,
            malfunction: 100,
            notes: '1920s',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '12-gauge Shotgun (2B)',
            damage: '4d6 / 2d6 / 1d6',
            range: '10/20/50 yards',
            attacks: '1 or 2',
            ammo: 2,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '12-gauge Shotgun (Pump)',
            damage: '4d6 / 2d6 / 1d6',
            range: '10/20/50 yards',
            attacks: '1',
            ammo: 5,
            malfunction: 100,
            notes: 'Modern',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '12-gauge Shotgun (semi-auto)',
            damage: '4d6 / 2d6 / 1d6',
            range: '10/20/50 yards',
            attacks: '1 (2)',
            ammo: 5,
            malfunction: 100,
            notes: 'Modern',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '12-gauge Shotgun (2B sawed off)',
            damage: '4d6 / 2d6 / 1d6',
            range: '5/10 yards',
            attacks: '1 or 2',
            ammo: 2,
            malfunction: 100,
            notes: '1920s',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '10-gauge Shotgun (2B)',
            damage: '4d6 + 2 / 2d6 + 1 / 1d4',
            range: '10/20/50 yards',
            attacks: '1 or 2',
            ammo: 2,
            malfunction: 100,
            notes: '1920s Rare',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '12-gauge Benelli M3 (folding stock)',
            damage: '4d6 / 2d6 / 1d6',
            range: '10/20/50 yards',
            attacks: '1 (2)',
            ammo: 7,
            malfunction: 100,
            notes: 'Modern',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '12-gauge SPAS (folding stock)',
            damage: '4d6 / 2d6 / 1d6',
            range: '10/20/50 yards',
            attacks: '1',
            ammo: 8,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (shotgun)',
            reference: 'CoC-IH:252',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'AK-47 or AKM',
            damage: '2d6 + 1',
            range: '100 yards',
            attacks: '1 (2) or full auto',
            ammo: 30,
            malfunction: 100,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'AK-74',
            damage: '2d6',
            range: '110 yards',
            attacks: '1 (2) or full auto',
            ammo: 30,
            malfunction: 97,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Barrett Model 82',
            damage: '2d10 + 1d8 + 6',
            range: '250 yards',
            attacks: '1',
            ammo: 11,
            malfunction: 96,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'FN FAL Light Automatic',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: '1 (2) or burst 3',
            ammo: 20,
            malfunction: 97,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Galil Assault Rifle',
            damage: '2d6',
            range: '110 yards',
            attacks: '1 or full auto',
            ammo: 20,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'M16A2',
            damage: '2d6',
            range: '110 yards',
            attacks: '1 (2) or burst 3',
            ammo: 30,
            malfunction: 97,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'M4',
            damage: '2d6',
            range: '90 yards',
            attacks: '1 (2) or burst 3',
            ammo: 30,
            malfunction: 97,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Steyr AUG',
            damage: '2d6',
            range: '110 yards',
            attacks: '1 (2) or full auto',
            ammo: 30,
            malfunction: 99,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Beretta M70/90',
            damage: '2d6',
            range: '110 yards',
            attacks: '1 or full auto',
            ammo: 30,
            malfunction: 99,
            notes: 'Modern',
            skill: 'Firearms (rifle)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Bergmann-MP18/1 MP28/1',
            damage: '1d10',
            range: '20 yards',
            attacks: '1 (2) or full auto',
            ammo: 20,
            malfunction: 96,
            notes: '1920s',
            skill: 'Firearms (SMG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Heckler & Koch MP5',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (2) or full auto',
            ammo: 15,
            malfunction: 96,
            notes: 'Modern',
            skill: 'Firearms (SMG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Ingram MAC-11',
            damage: '1d10',
            range: '15 yards',
            attacks: '1 (3) or full auto',
            ammo: 32,
            malfunction: 96,
            notes: 'Modern',
            skill: 'Firearms (SMG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Skorpion SMG',
            damage: '1d8',
            range: '15 yards',
            attacks: '1 (3) or full auto',
            ammo: 20,
            malfunction: 96,
            notes: 'Modern',
            skill: 'Firearms (SMG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Thompson',
            damage: '1d10 + 2',
            range: '20 yards',
            attacks: '1 or full auto',
            ammo: 20,
            malfunction: 96,
            notes: '1920s',
            skill: 'Firearms (SMG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Uzi SMG',
            damage: '1d10',
            range: '20 yards',
            attacks: '1 (2) or full auto',
            ammo: 32,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (SMG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Model 1882 Gatling Gun',
            damage: '2d6 + 4',
            range: '100 yards',
            attacks: 'Full auto',
            ammo: 200,
            malfunction: 96,
            notes: '1920s, Rare',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Browning Auto Rifle M1918',
            damage: '2d6 + 4',
            range: '90 yards',
            attacks: '1 (2) or full auto',
            ammo: 20,
            malfunction: 100,
            notes: '1920s',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '.30 Browning M1917A1',
            damage: '2d6 + 4',
            range: '150 yards',
            attacks: 'Full auto',
            ammo: 250,
            malfunction: 96,
            notes: '1920s',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Bren Gun',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: '1 or full auto',
            ammo: 30,
            malfunction: 96,
            notes: '1920s',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Mark I Lewis Gun',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: 'Full auto',
            ammo: 47,
            malfunction: 96,
            notes: '1920s',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Minigun',
            damage: '2d6 + 4',
            range: '200 yards',
            attacks: 'Full auto',
            ammo: 4000,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'FN Minimi 5.56mm',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: 'Full auto',
            ammo: 30,
            malfunction: 99,
            notes: 'Modern',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Vickers .303 Machine Gun',
            damage: '2d6 + 4',
            range: '110 yards',
            attacks: 'Full auto',
            ammo: 250,
            malfunction: 99,
            notes: '1920s',
            skill: 'Firearms (MG)',
            reference: 'CoC-IH:253',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Molotov Cocktail',
            damage: '2d6 + burn',
            range: '{strength} / 5 yards',
            attacks: '1/2',
            ammo: 1,
            malfunction: 95,
            notes: '1920s, Modern',
            skill: 'Throw',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Signal Handgun (Flare gun)',
            damage: '1d10 + 1d3 burn',
            range: '10',
            attacks: '1/2',
            ammo: 1,
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Firearms (HG)',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'M79 Grenade Launcher',
            damage: '3d10 / 2 yards',
            range: '20',
            attacks: '1/3',
            ammo: 1,
            malfunction: 99,
            notes: 'Modern',
            skill: 'Firearms (Heavy)',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Dynamite Stick*',
            damage: '4d10 / 3 yards',
            range: '{strength} / 5 yards',
            attacks: '1/2',
            ammo: 1,
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Throw',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Blasting Cap',
            damage: '2d10 / 1 yard',
            range: '1 yard',
            attacks: 'N/A',
            ammo: 'One use',
            malfunction: 100,
            notes: '1920s, Modern',
            skill: 'Electrical Repair',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Pipe Bomb',
            damage: '1d10 / 3 yards',
            range: '3 yards',
            attacks: 'In place',
            ammo: 'One use',
            malfunction: 95,
            notes: '1920s, Modern',
            skill: 'Demolitions',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Plastique (C-4), 4 oz.',
            damage: '6d10 / 3 yards',
            range: '3 yards',
            attacks: 'In place',
            ammo: 'One use',
            malfunction: 99,
            notes: 'Modern',
            skill: 'Demolitions',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Hand Grenade*',
            damage: '4d10 / 3 yards',
            range: '{strength} / 5 yards',
            attacks: '1/2',
            ammo: 1,
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Throw',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '81mm Mortar',
            damage: '6d10 / 6 yards',
            range: '500 yards',
            attacks: '1',
            ammo: 'Separate',
            malfunction: 100,
            notes: 'Modern',
            skill: 'Artillery',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '75mm Field Gun',
            damage: '10d10 / 2 yards',
            range: '500 yards',
            attacks: '1/4',
            ammo: 'Separate',
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Artillery',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: '120mm Tank Gun (stabilized)',
            damage: '15d10 / 4 yards',
            range: '2,000 yards',
            attacks: '1',
            ammo: 'Separate',
            malfunction: 100,
            notes: 'Modern',
            skill: 'Artillery',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Ship-mounted 5-inch rifle, stabilized',
            damage: '12d10 / 4 yards',
            range: '3,000 yards',
            attacks: '1',
            ammo: 'Auto-magazine',
            malfunction: 98,
            notes: 'Modern',
            skill: 'Artillery',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Anti-Personnel Mine',
            damage: '4d10 / 5 yards',
            range: '5 yards',
            attacks: 'In place',
            ammo: 'One use',
            malfunction: 99,
            notes: '1920s, Modern',
            skill: 'Demolitions',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Claymore Mine',
            damage: '6d6 / 20 yards',
            range: '20 yards',
            attacks: 'In place',
            ammo: 'One use',
            malfunction: 99,
            notes: 'Modern',
            skill: 'Demolitions',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'Flamethrower',
            damage: '2d6 + burn',
            range: '25 yards',
            attacks: '1',
            ammo: 'At least 10',
            malfunction: 93,
            notes: '1920s, Modern',
            skill: 'Firearms (Flamethrower)',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
        {
            name: 'LAW*',
            damage: '8d10 / 1 yard',
            range: '150 yards',
            attacks: '1',
            ammo: 1,
            malfunction: 98,
            notes: 'Modern',
            skill: 'Firearms (Heavy)',
            reference: 'CoC-IH:254',
            official: true,
            owner: null,
            scope: 'public',
        },
    ];

    // Deletes ALL existing entries
    await knex('coc_weapon').del();

    // Inserts seed entries
    await knex('coc_weapon').insert(weapons);
}

//----------------------------------------------------------------------------------------------------------------------
