id: genesys-ability-trained-mount
name: Trained Mount
description: Adds <boost></boost> equal to ranks in Trained Mount to another character's Riding checks while mounted on
  this character.
reference: SotC
