#-----------------------------------------------------------------------------------------------------------------------
# Configuration for RPGKeeper
#-----------------------------------------------------------------------------------------------------------------------

# HTTP Server configuration
http:
  host: '0.0.0.0'
  port: 5678
  secure: false

# Database
database:
  client: "better-sqlite3"
  connection:
    filename: "db/rpgk.db"
  useNullAsDefault: true

# Authentication configuration
auth:
  session:
    key: 'rpgk_session'
    secret: $SESSION_SECRET
  google:
    clientID: $CLIENT_ID
    clientSecret: $CLIENT_SECRET

#-----------------------------------------------------------------------------------------------------------------------
