- abbr: CoC-IH
  name: Call of Cthulhu Investigator Handbook
  productCode: CHA23136
- abbr: CoC-RK
  name: Call of Cthulhu Keeper Rulebook
  productCode: CHA23135
- abbr: HB
  name: Homebrew
  productCode: HB999
