/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BBadge: typeof import('bootstrap-vue-next')['BBadge']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BButtonGroup: typeof import('bootstrap-vue-next')['BButtonGroup']
    BButtonToolbar: typeof import('bootstrap-vue-next')['BButtonToolbar']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCol: typeof import('bootstrap-vue-next')['BCol']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownDivider: typeof import('bootstrap-vue-next')['BDropdownDivider']
    BDropdownForm: typeof import('bootstrap-vue-next')['BDropdownForm']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormRadio: typeof import('bootstrap-vue-next')['BFormRadio']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BFormRow: typeof import('bootstrap-vue-next')['BFormRow']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormSpinbutton: typeof import('bootstrap-vue-next')['BFormSpinbutton']
    BImg: typeof import('bootstrap-vue-next')['BImg']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-next')['BInputGroupAppend']
    BInputGroupPrepend: typeof import('bootstrap-vue-next')['BInputGroupPrepend']
    BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
    BListGroup: typeof import('bootstrap-vue-next')['BListGroup']
    BListGroupItem: typeof import('bootstrap-vue-next')['BListGroupItem']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    BPopover: typeof import('bootstrap-vue-next')['BPopover']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    BRow: typeof import('bootstrap-vue-next')['BRow']
    BTab: typeof import('bootstrap-vue-next')['BTab']
    BTable: typeof import('bootstrap-vue-next')['BTable']
    BTableLite: typeof import('bootstrap-vue-next')['BTableLite']
    BTableSimple: typeof import('bootstrap-vue-next')['BTableSimple']
    BTabs: typeof import('bootstrap-vue-next')['BTabs']
    BTbody: typeof import('bootstrap-vue-next')['BTbody']
    BTd: typeof import('bootstrap-vue-next')['BTd']
    BTh: typeof import('bootstrap-vue-next')['BTh']
    BThead: typeof import('bootstrap-vue-next')['BThead']
    BToastOrchestrator: typeof import('bootstrap-vue-next')['BToastOrchestrator']
    BTooltip: typeof import('bootstrap-vue-next')['BTooltip']
    BTr: typeof import('bootstrap-vue-next')['BTr']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface ComponentCustomProperties {
    vBColorMode: typeof import('bootstrap-vue-next')['vBColorMode']
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}
